//! generated by runtime/tools/gen-fonts.py from runtime/fonts/; do not edit by hand.
//! the imported faces in wire order, and where each one sits in faces.bin. face.zig reads
//! the blob and describes its layout.

pub const Name = enum(u8) { chunky6, chunky6x, light6, light6x, chunky8, chunky8x, chunky8x6, light8, light8x, light8x6, tiny5, @"tiny5-duo", @"tiny5-mono", phoenix, @"phoenix-2y", @"phoenix-8x14", @"ibm-iso8", @"apricot-xenc", @"robotron-a7100", @"ibm-vga" };

/// `height` is the trimmed line box; `index` and `bitmaps` are byte offsets into `blob`
pub const Metrics = struct { height: u8, count: u16, index: u32, bitmaps: u32 };

pub const metrics = [_]Metrics{
    .{ .height = 6, .count = 441, .index = 0, .bitmaps = 4851 }, // chunky6
    .{ .height = 6, .count = 441, .index = 5938, .bitmaps = 10789 }, // chunky6x
    .{ .height = 6, .count = 441, .index = 11976, .bitmaps = 16827 }, // light6
    .{ .height = 6, .count = 441, .index = 17881, .bitmaps = 22732 }, // light6x
    .{ .height = 8, .count = 731, .index = 23881, .bitmaps = 31922 }, // chunky8
    .{ .height = 8, .count = 731, .index = 34332, .bitmaps = 42373 }, // chunky8x
    .{ .height = 8, .count = 463, .index = 44782, .bitmaps = 49875 }, // chunky8x6
    .{ .height = 8, .count = 731, .index = 51931, .bitmaps = 59972 }, // light8
    .{ .height = 8, .count = 731, .index = 62345, .bitmaps = 70386 }, // light8x
    .{ .height = 8, .count = 463, .index = 72758, .bitmaps = 77851 }, // light8x6
    .{ .height = 11, .count = 1941, .index = 79862, .bitmaps = 101213 }, // tiny5
    .{ .height = 11, .count = 1941, .index = 107506, .bitmaps = 128857 }, // tiny5-duo
    .{ .height = 11, .count = 2286, .index = 136839, .bitmaps = 161985 }, // tiny5-mono
    .{ .height = 8, .count = 255, .index = 171157, .bitmaps = 173962 }, // phoenix
    .{ .height = 16, .count = 255, .index = 175554, .bitmaps = 178359 }, // phoenix-2y
    .{ .height = 14, .count = 255, .index = 181543, .bitmaps = 184348 }, // phoenix-8x14
    .{ .height = 15, .count = 255, .index = 186505, .bitmaps = 189310 }, // ibm-iso8
    .{ .height = 14, .count = 255, .index = 191673, .bitmaps = 194478 }, // apricot-xenc
    .{ .height = 11, .count = 255, .index = 196748, .bitmaps = 199553 }, // robotron-a7100
    .{ .height = 15, .count = 787, .index = 201587, .bitmaps = 210244 }, // ibm-vga
};

pub const blob: []const u8 = @embedFile("faces.bin");
