#!/usr/bin/env python3
"""generate src/scene/zones.zig: iana zone names mapped to the posix tz rule each zone follows
from now on, taken from the footer of the tzif files in a zoneinfo directory (the mac's
/usr/share/zoneinfo by default), plus each zone's reference coordinates from zone.tab, which is
what places the device for the sunrise/sunset schedule. the output is committed, so builds never
depend on the host.

  tools/gen-zones.py [zoneinfo-dir] > src/scene/zones.zig

zones whose rule uses julian-day transitions (two african zones on permanent summer time) are
stored as their summer-time fixed offset, which is what the rule amounts to for a clock.
"""
import hashlib, os, re, sys

root = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/zoneinfo"
skip_dirs = {"posix", "right"}
skip_files = {"posixrules", "Factory", "localtime"}
zones = {}
digests = {}  # tzif content, to give a link zone its target's coordinates
for d, _, files in os.walk(root):
    rel = os.path.relpath(d, root)
    if rel.split("/")[0] in skip_dirs:
        continue
    for f in files:
        p = os.path.join(d, f)
        name = os.path.relpath(p, root)
        if name in skip_files or not os.path.isfile(p):
            continue
        data = open(p, "rb").read()
        if data[:4] != b"TZif":
            continue
        rule = data.rstrip(b"\n").rsplit(b"\n", 1)[-1].decode()
        if not rule:
            continue
        if "J" in rule.split(",", 1)[-1] and "," in rule:
            # permanent summer time expressed as a julian-day rule: keep the summer offset only
            m = re.match(r"^(<[^>]+>|[A-Za-z]{3,})([+-]?\d+(?::\d+)*)(<[^>]+>|[A-Za-z]{3,})([+-]?\d+(?::\d+)*)?,", rule)
            if not m:
                continue
            std_off = m.group(2)
            dst_off = m.group(4) or (str(int(std_off.split(":")[0]) - 1))
            rule = f"{m.group(3)}{dst_off}"
        zones[name] = rule
        digests[name] = hashlib.sha256(data).hexdigest()

# zone.tab carries the reference coordinates of every canonical zone in iso 6709. link zones are
# absent from it, so they take the coordinates of whichever canonical zone has the same tzif bytes.
def iso6709(text):
    """(latitude, longitude) in hundredths of a degree, rounded."""
    m = re.fullmatch(r"([+-]\d{2})(\d{2})(\d{2})?([+-]\d{3})(\d{2})(\d{2})?", text)
    if not m:
        raise ValueError(f"unparsable coordinate {text!r}")
    def deg(d, mi, se):
        v = abs(int(d)) + int(mi) / 60 + int(se or 0) / 3600
        return round(v * 100) * (-1 if d[0] == "-" else 1)
    return deg(m.group(1), m.group(2), m.group(3)), deg(m.group(4), m.group(5), m.group(6))

unknown = 32767  # no coordinates: the user has to give a latitude and longitude of their own
coords = {}
by_digest = {}
tab = os.path.join(root, "zone.tab")
if os.path.exists(tab):
    for line in open(tab):
        if line.startswith("#") or not line.strip():
            continue
        _, point, name = line.split("\t")[:3]
        name = name.strip()  # a zone with no comment ends the line, newline and all
        coords[name] = iso6709(point)
        if name in digests:
            by_digest.setdefault(digests[name], coords[name])
for name in zones:
    if name not in coords and digests.get(name) in by_digest:
        coords[name] = by_digest[digests[name]]

names = sorted(zones)
blob = "".join(f"{n}\\x00{zones[n]}\\x00" for n in names)
print("//! iana zone names and the posix tz rule each follows from now on, generated by")
print("//! tools/gen-zones.py from the tzif footers of a zoneinfo directory. one blob of")
print('//! "name\\0rule\\0" records, sorted by name; looked up by a linear scan at configuration time,')
print("//! with the zone reference points of zone.tab alongside, in the same order.")
placed = [n for n in names if n in coords]
print(f"pub const count = {len(names)};")
print(f'pub const blob = "{blob}";')
print("// the reference point of each zone, in hundredths of a degree, in the same order as the")
print(f"// blob's records; {unknown} means the zone has none ({len(names) - len(placed)} of {len(names)}).")
print("pub const Point = struct { lat_c: i16, lon_c: i16 };")
print("pub const unplaced: i16 = %d;" % unknown)
print("pub const points = [count]Point{")
for n in names:
    lat, lon = coords.get(n, (unknown, unknown))
    print(f"    .{{ .lat_c = {lat}, .lon_c = {lon} }}, // {n}")
print("};")
