#!/usr/bin/env python3
"""generate src/scene/zones.zig: iana zone names mapped to the posix tz rule each zone follows
from now on, taken from the footer of the tzif files in a zoneinfo directory (the mac's
/usr/share/zoneinfo by default). the output is committed, so builds never depend on the host.

  tools/gen-zones.py [zoneinfo-dir] > src/scene/zones.zig

zones whose rule uses julian-day transitions (two african zones on permanent summer time) are
stored as their summer-time fixed offset, which is what the rule amounts to for a clock.
"""
import os, re, sys

root = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/zoneinfo"
skip_dirs = {"posix", "right"}
skip_files = {"posixrules", "Factory", "localtime"}
zones = {}
for d, _, files in os.walk(root):
    rel = os.path.relpath(d, root)
    if rel.split("/")[0] in skip_dirs:
        continue
    for f in files:
        p = os.path.join(d, f)
        name = os.path.relpath(p, root)
        if name in skip_files or not os.path.isfile(p):
            continue
        data = open(p, "rb").read()
        if data[:4] != b"TZif":
            continue
        rule = data.rstrip(b"\n").rsplit(b"\n", 1)[-1].decode()
        if not rule:
            continue
        if "J" in rule.split(",", 1)[-1] and "," in rule:
            # permanent summer time expressed as a julian-day rule: keep the summer offset only
            m = re.match(r"^(<[^>]+>|[A-Za-z]{3,})([+-]?\d+(?::\d+)*)(<[^>]+>|[A-Za-z]{3,})([+-]?\d+(?::\d+)*)?,", rule)
            if not m:
                continue
            std_off = m.group(2)
            dst_off = m.group(4) or (str(int(std_off.split(":")[0]) - 1))
            rule = f"{m.group(3)}{dst_off}"
        zones[name] = rule

names = sorted(zones)
blob = "".join(f"{n}\\x00{zones[n]}\\x00" for n in names)
print("//! iana zone names and the posix tz rule each follows from now on, generated by")
print("//! tools/gen-zones.py from the tzif footers of a zoneinfo directory. one blob of")
print('//! "name\\0rule\\0" records, sorted by name; looked up by a linear scan at configuration time.')
print(f"pub const count = {len(names)};")
print(f'pub const blob = "{blob}";')
